version: "1.0"
info:
  model: int-scaffold
packages:
- name: DimaTest1125_9Project
  gitServerName: dima
  gitUrl: https://github.com/deemashlayer
  gitUsername: deemashlayer
  gitBranch: main
services:
- serviceName: project.dimatest1125_9.integrations:jghfd
  packages:
  - name: DimaTest1125_9Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
